project:
  type: website
  output-dir: _site
  pre-render: print_quarto_config.py
  render:
    - landing_page.qmd
    - L01LinearEquations.qmd


website:
  title: "Geometric Algorithms"
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
    - landing_page.qmd
    - L01LinearEquations.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute: 
  freeze: auto # see https://quarto.org/docs/projects/code-execution.html#freeze
  cache: true # see https://quarto.org/docs/projects/code-execution.html#cache
