project:
  output-dir: _revealjs
  pre-render: print_quarto_config.py
  render:
    - L01LinearEquations.qmd


format:
  revealjs:
    footer: "CS 132 Geometric Algorithms"
    scrollable: true
    slide-number: c/t
    show-slide-number: all
    chalkboard: true
    smaller: true
    html-math-method: mathjax
    echo: true
    code-fold: true
    # eventually I think we want to use this option but I don't want
    # to enable it so late in the semester since it will effect all
    # the earlier slides. See
    # https://quarto.org/docs/presentations/revealjs/advanced.html#stretch
    auto-stretch: false
    theme: [beige, slide_theme_adjustments.scss]
    transition: fade

# this is an example of how to override CSS.  
# not normally using the YAML titles
include-in-header: 
  - text: |
      <style>
      #title-slide .title {
        font-size: 2em;
        color: #b22222;
      }
      </style>

execute: 
  freeze: auto # see https://quarto.org/docs/projects/code-execution.html#freeze
  cache: true  # see https://quarto.org/docs/projects/code-execution.html#cache
