project:
  output-dir: _revealjs
  pre-render: print_quarto_config.py
  render:
    - L01LinearEquations.qmd
    - L02Numerics.qmd
    - L03RowReductions.qmd
    - L04VectorEquations.qmd


format:
  revealjs:
    footer: "CS 132 Geometric Algorithms"
    scrollable: true
    slide-number: c/t
    show-slide-number: all
    chalkboard: true
    smaller: true
    html-math-method: mathjax
    echo: true
    code-fold: false
    auto-stretch: false
    theme: [beige, slide_theme_adjustments.scss]
    transition: fade

# this is an example of how to override CSS.  
# not normally using the YAML titles
include-in-header: 
  - text: |
      <style>
      #title-slide .title {
        font-size: 2em;
      }
      </style>

execute: 
  freeze: auto # see https://quarto.org/docs/projects/code-execution.html#freeze
  cache: true  # see https://quarto.org/docs/projects/code-execution.html#cache
