project:
  type: website
  output-dir: _site
  pre-render: print_quarto_config.py
  render:
    - landing_page.qmd
    - L01LinearEquations.qmd
    - L02Numerics.qmd
    - L03RowReductions.qmd
    - L04VectorEquations.qmd
    - L05Axb.qmd
    - L06LinearIndependence.qmd
    - L07LinearTransformations.qmd
    - L08MatrixofLinearTransformations.qmd
    - L09MatrixOperations.qmd
    - L10MatrixInverse.qmd
    - L11MarkovChains.qmd
    - L12MatrixFactorizations.qmd
    - L13ComputerGraphics.qmd
    - L14Subspaces.qmd

website:
  title: "Geometric Algorithms"
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    logo: images/DiagramAR-icon.png
    contents:
    - landing_page.qmd
    - L01LinearEquations.qmd
    - L02Numerics.qmd
    - L03RowReductions.qmd
    - L04VectorEquations.qmd
    - L05Axb.qmd
    - L06LinearIndependence.qmd
    - L07LinearTransformations.qmd
    - L08MatrixofLinearTransformations.qmd
    - L09MatrixOperations.qmd
    - L10MatrixInverse.qmd
    - L11MarkovChains.qmd
    - L12MatrixFactorizations.qmd
    - L13ComputerGraphics.qmd
    - L14Subspaces.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    html-math-method: mathjax

execute: 
  freeze: auto # see https://quarto.org/docs/projects/code-execution.html#freeze
  cache: true # see https://quarto.org/docs/projects/code-execution.html#cache
